const EMPLOYEES = {
  "100": {
    employeeName: "مهرزاد شاه رضایی",
    password: "123456",
    payslips: {
      "فروردین": "1405-01.jpg",
      "اردیبهشت": "",
      "خرداد": "",
      "تیر": "",
      "مرداد": "",
      "شهریور": "",
      "مهر": "",
      "آبان": "",
      "آذر": "",
      "دی": "",
      "بهمن": "",
      "اسفند": ""
    }
  },

  "103": { employeeName: "نیما عارف", password: "103", payslips: {} },
  "106": { employeeName: "سید جعفر رسول مطهری", password: "106", payslips: {} },
  "109": { employeeName: "سید عبدالرسول مطهری", password: "109", payslips: {} },
  "119": { employeeName: "کیوان ردایی", password: "119", payslips: {} },
  "122": { employeeName: "یدالله بابایی", password: "122", payslips: {} },
  "132": { employeeName: "محمد رضا ولیزاده", password: "132", payslips: {} },
  "135": { employeeName: "سید جعفر طباطبایی", password: "135", payslips: {} },
  "147": { employeeName: "علی اکرادی", password: "147", payslips: {} },
  "148": { employeeName: "محمد رضا بالسینی", password: "148", payslips: {} },
  "162": { employeeName: "دکتر محمدرضا شکیبامنش", password: "162", payslips: {} },
  "165": { employeeName: "محمد زارعی", password: "165", payslips: {} },
  "172": { employeeName: "مسعود کیالاشکی", password: "172", payslips: {} },
  "177": { employeeName: "حسن نیگسان", password: "177", payslips: {} },
  "181": { employeeName: "رضا عبدالکریم", password: "181", payslips: {} },
  "189": { employeeName: "محمدرضا کاهه", password: "189", payslips: {} },
  "192": { employeeName: "اصغر محققی", password: "192", payslips: {} },
  "198": { employeeName: "اتابک گنجی زاده", password: "198", payslips: {} },
  "203": { employeeName: "علیرضا سرافرازی", password: "203", payslips: {} },
  "219": { employeeName: "دکتر ندا کاری", password: "219", payslips: {} },
  "220": { employeeName: "میلاد احمد بیگی", password: "220", payslips: {} },
  "221": { employeeName: "عیسی چلیکی", password: "221", payslips: {} },
  "222": { employeeName: "طه گونه", password: "222", payslips: {} },
  "225": { employeeName: "پرنیا راحتی", password: "225", payslips: {} },
  "228": { employeeName: "دکتر فرینوش شمس", password: "228", payslips: {} },
  "229": { employeeName: "غزل جعفر بگلو", password: "229", payslips: {} },
  "232": { employeeName: "فاطمه علیزاده", password: "232", payslips: {} },
  "233": { employeeName: "ابوالفضل وشتانی", password: "233", payslips: {} },
  "234": { employeeName: "مهدی حسن نژاد", password: "234", payslips: {} },
  "235": { employeeName: "فاطمه صادقی", password: "235", payslips: {} },
  "236": { employeeName: "حمید رضا احمد بیگی", password: "236", payslips: {} },
  "237": { employeeName: "نسیم ماه انباری", password: "237", payslips: {} },
  "240": { employeeName: "یاسر گیلانی", password: "240", payslips: {} },
  "241": { employeeName: "الهه جمالی", password: "241", payslips: {} },
  "243": { employeeName: "آتنا اسدی", password: "243", payslips: {} },
  "244": { employeeName: "سعید دارابی", password: "244", payslips: {} },
  "246": { employeeName: "دکتر فاطمه آقاجانیان", password: "246", payslips: {} },
  "247": { employeeName: "پارسا برومند", password: "247", payslips: {} },
  "248": { employeeName: "محمد ذبیحی", password: "248", payslips: {} },
  "250": { employeeName: "بهرام غفاری", password: "250", payslips: {} },
  "251": { employeeName: "نام پرسنل ثبت نشده", password: "251", payslips: {} }
};
